name: Test Xcode target

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Xcode
      uses: actions/setup-xcode@v2
      with:
        xcode-version: '12.x' # replace with your desired Xcode version
    - name: Build Xcode target
      run: xcodebuild -project Turf.xcodeproj -scheme TurfTests -destination 'platform=iOS Simulator,name=iPhone 12' test
